server:
  host: 0.0.0.0
  port: 8000

agent:
  model: gemini-3.1-flash-lite
  max_turns: 50
  temperature: 1.0
  openai_api_key: sk-FVXkc4rTrgVFEfbB1cD65aF6Ad1f4501Ac88346e09Ea5433
  openai_base_url: https://api.v3.cm/v1
  mcp_sse_url: http://mcp-gateway:9000/sse
  mcp_auth_token: ""
  langfuse:
    enabled: true
    host: https://us.cloud.langfuse.com
    public_key: "pk-lf-e4c024fa-db84-432a-a284-07dc7de6aa44"
    secret_key: "sk-lf-cc887c45-7975-4af6-aab7-dee9ece0a9d1"
    flush_at: 16
    flush_interval: 0.5
    request_timeout: 5.0
